### ISSUE TITLE
Much needed

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-android#1]
While Nitroshare is useful for desktop, the real feature that is missing is to be able to beam files from Android device to PC over LAN.

**Comment by nathan-osman** [comment]
This is planned. I am hard at work rewriting the core of the desktop application for the next release. I am hoping to have an Android app (at least an alpha release) available at the same time.

Believe me, I really want an Android version too - I'm working as hard as I can to make this happen.

**Comment by techtonik** [comment]
Do you have a spec of what are you rewriting? Maybe people can help if they know what to do.

**Comment by nathan-osman** [comment]
The wiki describes the transfer protocol. If someone wanted to implement that on Android, that would be alright. The desktop version is in flux right now as I finalize the API (which I hope to do by the end of the month).

**Comment by nathan-osman** [comment]
...and **done!**

NitroShare for Android is now in closed alpha. The current release supports transfers _between_ Android devices and I'll be releasing a new version of the desktop client soon to allow transfers between Android and PC clients.

If anyone wants to help test, send me your Gmail address and I'll add you to the alpha testing team.

**Comment by techtonik** [comment]
This is the wiki referenced above to transfer protocol https://github.com/nitroshare/nitroshare-desktop/wiki/Transfer-Protocol in desktop project. I guess wiki for this android project should be disabled to avoid confusing. But frankly, I'd better see docs committed to some repository to make them searchable.

**Comment by nathan-osman** [comment]
The transfer protocol is identical to the one used on the desktop client and the discovery protocol is mDNS, which already has a published spec. (even if [it isn't always implemented correctly](https://github.com/lathiat/avahi/issues/104)).
