### ISSUE TITLE
Can't compile (enable Travis CI?)

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-android#20]
```
>gradlew.bat
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/3.3/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

> Starting Daemon
```

Maybe provide Travis builds? I can send you PR if you enable it at https://travis-ci.org/nitroshare/

**Comment by nathan-osman** [comment]
This isn't an error caused by NitroShare for Android but rather [an issue with the JVM requesting too much memory](http://stackoverflow.com/questions/26143740/getting-gradle-error-could-not-reserve-enough-space-for-object-heap-constantly).

**Comment by nathan-osman** [comment]
That being said, setting up a build for Travis-CI sounds like a good idea. If you send a PR, I will gladly enable it :smile:

**Comment by techtonik** [comment]
I haven't found how to download .apk builds from Travis, but I guess the first problem is to get the build running.

**Comment by SearchPeoples** [comment]
got the same error in Visual Studio 2015 with cordova 5.1.1 under Windows 10.

To solve the issue, set this environment variable:

_JAVA_OPTIONS=-Xmx512M
Right click on start-button and open "System"
Go to Advanced system settings on the left side
Click the button "Environment Variables ..."
In System Variables, click "New..."
New Variable Name: _JAVA_OPTIONS
New Variable Value: -Xmx512M
Click OK
Restart Visual Studio, so the variable is picked up
This Article point me in the right direction. I did change the instructions a littel bit, so they fits to Windows 10.

Hope it helps someone!
