### ISSUE TITLE
No Android devices visible in desktop 0.3.3 (Ubuntu)

### ISSUE THREAD

**Issue by techtonik** [nitroshare/nitroshare-android#27]
There are no devices visible on Ubuntu when sending files to Android. (

**Comment by nathan-osman** [comment]
NitroShare 0.3.3 doesn't use mDNS and therefore transfers are not possible between it and an Android client.

**Comment by techtonik** [comment]
Maybe it should be versioned as 1.0.0 then?

It would be nice to see https://github.com/nitroshare/nitroshare-desktop/wiki/Transfer-Protocol fixed somewhere (maybe it a blog post) with a comparison to new scheme.

And it looks like Wiki in this project is empty.

**Comment by nathan-osman** [comment]
The transfer protocol hasn't changed. Only the discovery protocol. I won't document the internals of mDNS but I do see the value in describing how the process works (the service type, etc.).

My original goal was to keep the version numbers inline with the desktop client to avoid confusion. However, I soon realized that version 0.4.0 for the desktop was still a long ways from completion and I wanted to get the Android app up and running. Therefore, I am going to be releasing 0.3.4 first alongside the Android app and then I can focus on getting 0.4.0 ready to go. (I have some really exciting features planned (and partially completed) for it.)

**Comment by techtonik** [comment]
I guess this is fixed by some of the last 4 days commits - https://github.com/nitroshare/qmdnsengine/commits/c1972231604bc5daa5066342b0356dfc5ed2f32b

**Comment by techtonik** [comment]
Oh. No this is for other way around.

**Comment by nathan-osman** [comment]
I finally fixed another bug in QMdnsEngine and I _think_ it may be the cause of this issue. Could you please confirm?

**Comment by rapgro** [comment]
see also #40

**Comment by techtonik** [comment]
0.3.4 Ubuntu Desktop can see Android device, but fails to send with `Failed: Connection` status.

**Comment by techtonik** [comment]
> There are no devices visible on Ubuntu when sending files to Android. (

Devices are now visible with 0.3.4 on Ubuntu 17.10, so this particular bug is fixed.
