### ISSUE TITLE
Toggle for listening mode in main view

### ISSUE THREAD

**Issue by Nemris** [nitroshare/nitroshare-android#36]
Good day.

I would like to suggest adding a button for toggling between the listening modes inside the main view of the app. This will save users quite a bunch of swipes, and it'll be appropriate as well, as the main view is used to monitor transfers.

**Comment by nathan-osman** [comment]
Perhaps something like [this suggestion](https://github.com/nitroshare/nitroshare-android/issues/26#issuecomment-306020285)? Once "exit" is added, it would terminate the listening mode.

**Comment by Nemris** [comment]
That'd be good, but an user would still be required to visit the main settings in order to turn the listening mode on, is it? My idea was to make both the activation and deactivation reachable with more ease. What do you think?

**Comment by nathan-osman** [comment]
The suggestion is to put it in the sliding menu on the main activity. (You can open it by swiping to the right from the left edge.)

**Comment by Nemris** [comment]
My bad. I intended it as if a button was put, that could only terminate the listening mode, but not start it. I wholeheartedly agree with the abovementioned suggestion, though. Will close the issue now.
