### ISSUE TITLE
Exit button only kills the app

### ISSUE THREAD

**Issue by Nemris** [nitroshare/nitroshare-android#37]
Good day.

I recently updated NitroShare to v0.4.0.30, and headed to its settings in order to turn on the receiving mode, and I confirmed that the usual notification was displayed.

Upon using the `Exit` button from the main view, NitroShare was killed and the notification disappeared as well, as expected. Starting the app again, though, reveals that the `Receive Transfers` setting is still active, but the notification does not appear.

## Steps to reproduce

1. Start Nitroshare.
2. Go to the settings and tick `Receive Transfers`. Observe that the notification, showing that NitroShare is listening, is displayed.
3. Return to the app's main view, swipe from the left and tap `Exit`; the app gets killed, and the notifications disappears.
4. Start NitroShare once more.
5. Go to the settings, and observe that the `Receive Transfers` setting is active, whilst the corresponding notification is not displayed.

## Expected behavior

Upon tapping `Exit` as of step 3, NitroShare should deactivate the `Receive Transfers` setting, before exiting.

## Device info

Device: I9195
OS: LineageOS 14.1
NitroShare: 0.4.0.30

**Comment by nathan-osman** [comment]
Exit isn't intended to change the `Receive Transfers` setting but to merely provide a temporary means of shutting down the application. As soon as you start the app again, the listening service will be restarted. The setting, rather, is intended to permanently disable listening for transfers.

From your "steps to reproduce" section, the only anomaly is in step 5 when the notification is not displayed upon restart. That is not correct behavior and therefore a bug.
