### ISSUE TITLE
Error Windows to Android

### ISSUE THREAD

**Issue by lvl0-i74134** [nitroshare/nitroshare-android#45]
Transferring is possible from Android to Windows but Windows to Android shows:

[unknown]
Failed: null

**Comment by lvl0-i74134** [comment]
Plus after attempting to change destination folder in Android, nothing changed.
Still: 
/Storage/emulated/0/Download/NitroShare

**Comment by ruralTom** [comment]
I've got the same error. Switching download folders works okay, but the error persists.

You cannot send a file from Windows to Android.

**Comment by boomt1337** [comment]
Weird. My V10 shared sucessfully to my Windows Computer, and again when sharing from computer to windows. Android*

**Comment by MaximilianKindshofer** [comment]
I have the same error sending files from w10 to android. Android to Windows works.

**Comment by Sopheus** [comment]
Same thing for me. I can receive from Android (Noughat) to Windows (64 home), but if I try to do so from Windows to Android, the transferring process just "sits" there for awhile and then just fails to transfer any file and return: connection timed out.

**Comment by nathan-osman** [comment]
Okay, I'm rolling out perqin's fix to the beta channel as we speak. I'm hoping this eliminates the problem. I'll push it to production if things go well.
