### ISSUE TITLE
Don t work on android

### ISSUE THREAD

**Issue by B4rabbas** [nitroshare/nitroshare-android#49]
I have nitrishare on my computer and my android too, on the same wifi but it donvt show the device when i want to transfer.

**Comment by boomt1337** [comment]
Give us more info please. What device is it you are trying to connect to? What Android Version and App Version do you have?

**Comment by contrapunctus-1** [comment]
Same problem here. NitroShare v0.4.0.38 from F-Droid on a Moto G 5s Plus (Android v7.1.1) and a Moto G4 Plus (Android v7.0). Neither device can see any devices when I try to send a file.

**Comment by boomt1337** [comment]
Can't repro, Nitroshare stable latest version, LG V10 Nougat. Maybe it's an version specific bug?

**Comment by boomt1337** [comment]
We require more info from OP

**Comment by contrapunctus-1** [comment]
I could test with more devices, but it'd be helpful if I could get the exact steps needed to successfully share a file, as I find the UI a little unclear and might be going about it the wrong way.

**Comment by kenhkelly** [comment]
I have the same issue, Moto G5s. Trying to send a mp4 file and getting "Failed: Host unreachable"

**Comment by abesty** [comment]
Same problem in lineage OS 14.1 🙄

**Comment by Endogen** [comment]
Me too, same problem in lineage OS 14.1 with OnePlus One (bacon)

**Comment by flamasweb** [comment]
Same problem in the latest Android version on Galaxy S9

**Comment by k3b** [comment]
Can you rename the ticket from "Don t work on android" to "android device is not visible on pc"?

Probably related: https://github.com/nitroshare/nitroshare-desktop/issues/194

To help finding out if this is a network and not an app problem:

You have a running wlan and both pc and android are connected to the same wlan?

Alternative your android is in wlan tethering mode and your pc is connected to the android-tethering hotspot?

* Can you [ping from android to the pc](https://forum.xda-developers.com/showthread.php?t=2250752) ?
* can you ping from pc to the android-device?

if one is false you likely have a network problem (firewall)

**Comment by flamasweb** [comment]
@k3b I can see my device from Mac and i'm able to share files from the S9 to the Mac but i'm not able to do the opposite

**Comment by B4rabbas** [comment]
Sorry for the late response :
So it's a Xiaomi redmi 5 plus
Running on 7.1.2 Nougat

I've tried on linux, mac & windows.
Since I'm using kde connect.

There is a build for windows https://binary-factory.kde.org/job/kdeconnect-kde_Nightly_win32/
And mac
https://soduto.com
