### ISSUE TITLE
Android devices not showing in Nitroshare desktop

### ISSUE THREAD

**Issue by hiep2000** [nitroshare/nitroshare-android#6]
My android phone is not showing in Nitroshare desktop (Windows), but sending from 2 androids works well.
My PC is connecting to router via cable, and the phone is connect on that same router.
![2017-03-07_104034](https://cloud.githubusercontent.com/assets/25681968/23640824/8efd3008-0322-11e7-9372-3c8b11865f99.png)

**Comment by nathan-osman** [comment]
The desktop client is not yet able to "see" Android devices. In more technical terms, the Android app uses mDNS and the desktop clients use IPv4 broadcast for discovery. I will be updating the desktop clients very soon to add mDNS support so that they can see each other. Until then, only Android => Android transfers are supported.

**Comment by techtonik** [comment]
It would be nice to read descriptions for both ways of peer discovery. mDNS seems much more complicated than dealing with IPv4 broadcasts.

**Comment by nathan-osman** [comment]
mDNS is indeed more complicated but necessary for IPv6 support and reduced network utilization.

**Comment by techtonik** [comment]
I once tried to create mDNS in Python, but it appeared that code to make those multicast packers is so low level and operating system specific that I abandoned the efforts. In the worst case it may require some privileges to work with raw sockets.

**Comment by nathan-osman** [comment]
It's not quite that bad. mDNS simply requires an interface that can send UDP packets and join a multicast group. Neither of those should require special privileges. I have some experimental Qt code that seems to be working now - other tools (Avahi browser, etc.) are able to discover the service. And the app is running as an ordinary user.

There was one issue I had to work around. QUdpSocket's `QAbstractSocket::ShareAddress` flag doesn't work properly so I had to manually set `SO_REUSEADDR` on the socket descriptor. But other than that, it works great.

**Comment by techtonik** [comment]
Apart from `SO_REUSEADDR`, which I also stumbled upon, I guess Python just doesn't have the sane API for joining a group - https://svn.python.org/projects/python/trunk/Demo/sockets/mcast.py 

Sane API is that of `chrome` - https://developer.chrome.com/apps/sockets_udp

**Comment by nathan-osman** [comment]
This is now ready for testing: https://www.facebook.com/nitroshare/posts/1812095739107909

**Comment by techtonik** [comment]
Facebook? But.. why?

**Comment by nathan-osman** [comment]
Here's the content of the post for convenience:

> Initial builds of NitroShare 0.3.4 for the desktop are finally here!
>
> These builds include support for transferring files with the Android app, which is (as of right now) entering public beta. Interested in testing? Use the links below to grab a copy of the app:
>
> The Android app can be installed from this page:  
https://play.google.com/store/apps/details?id=net.nitroshare.android
>
> macOS:  
> https://ci.quickmediasolutions.com/job/nitroshare/toolchain=macos&&x86_64&&clang/lastSuccessfulBuild/artifact/build/nitroshare-0.3.4-osx.dmg
>
> Win32:  
> https://ci.quickmediasolutions.com/job/nitroshare/toolchain=windows&&x86&&msvc2015/lastSuccessfulBuild/artifact/build/nitroshare-0.3.4-windows-x86.exe
>
> Win64:  
> https://ci.quickmediasolutions.com/job/nitroshare/toolchain=windows&&x86_64&&msvc2015/lastSuccessfulBuild/artifact/build/nitroshare-0.3.4-windows-x86_64.exe
>
> Ubuntu users can use the NitroShare Dev PPA:  
>https://launchpad.net/~george-edison55/+archive/ubuntu/nitroshare-dev

**Comment by techtonik** [comment]
That's much better. :D Thanks.

**Comment by ashjas** [comment]
@nathan-osman what do i do after adding the ppa on ubuntu?
there is nothing available of version 0.3.4

**Comment by ssipos90** [comment]
It still doesn't work..

**Comment by sbszulu** [comment]
Yes. It still doesn't work till today.

**Comment by ssipos90** [comment]
> Yes. It still doesn't work till today.

that's because there are no new releases since. I've switched to Dukto since ( https://sourceforge.net/projects/dukto/ )

**Comment by MarcoB-0049** [comment]
Have a nice day to you and the community!
I have now installed nitroshare again on LM18.3 for some time. The problem is that nitroshare does not recognize my Android 8 on the LM desktop. The communication via nitroshare between the devices installed in the DualBoot W10P/1903 works perfectly. Why does the LM-Desktop not find the Android in the same network or what has to be installed or which dependencies might be missing to detect this?
Many greetings 
MarcoB

**Comment by MBarnulf** [comment]
same issue, still today, can't view android devices from pc or linux
(fresh install of os (without any bloat) and software on all 3 of my devices, I suspect the issue come from the app)

**Comment by TVBZ** [comment]
Same here.. Just installed desktop app on W10 and Ubuntu, and Android app on phone. 
I can send from Android to Windows and Linux, but desktop app can't find the Android device,.. it's a 1-way street.

**Comment by techtonik** [comment]
It is better to open a new issue with as much info as possible.

Version of Android:
Version of Nitroshare on Android:
Version of Nitroshare on Desktop:
Version of OS and Desktop:

Maybe @nathan-osman added some debug logs that can be copy-pasted to troubleshoot the issue, but I am not sure.
